### ISSUE TITLE
Save Editor seems not working

### ISSUE THREAD

**Issue by GoranXXV** [turtle-insect/DQTreasure#1]
I'm currently play DQ Treasures in italian and I downloaded your save editor but if I open DarwinSaveData0, DarwinSaveData1 or DarwinSaveData99 it doesn't seem to work properly for both the save data

**Comment by turtle-insect** [comment]
Can you provide the save data?

**Comment by GoranXXV** [comment]
[0000000000000005.zip](https://github.com/turtle-insect/DQTreasure/files/10217901/0000000000000005.zip)
There are here

**Comment by turtle-insect** [comment]
thank you

update
https://github.com/turtle-insect/DQTreasure/commit/2e4e213f0c3cdb4b49b73b26409a3886bba43d72
